### ISSUE TITLE
After disabling SuiteAdvanced, no option to enable it again

### ISSUE THREAD

**Issue by martjag12** [burkybang/SuiteAdvanced-Feedback#103]
**Describe the bug**
After disabling SuiteAdvanced in account, I cannot find a way of disabling that again.
Tried that with home computer and office computer, no way to disable SuiteAdvanced on SB account. Although, I can see SuiteAdvanced enabled in all other accounts I am logging to.

Happened for my colleague as well after disabling SuiteAdvanced.

Answer: 

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. Disable SuiteAdvanced
2. Enable SuiteAdvanced action cannot be find. Started happening ~1-2 months ago.

Answer: 

___

**Expected behavior**
We should be able to activate SuiteAdvanced again after it is disabled on certain account.

Answer: 

___

**Screenshots**
Cannot add due to company policy, but can jump on a call to show an example.

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
Thank you for reporting the issue!

I haven't been able to determine the source of the issue yet, but I have a workaround that has 100% resolved the issue (so far) for one other user.

1. On a NetSuite page, open Chrome DevTools ([How to](https://developer.chrome.com/docs/devtools/open/))
2. Go to the Console tab
3. Run the following command
```
localStorage.removeItem('SuiteAdvanced Disabled');
```
4. Refresh the page

Since I don't know why the issue happened in the first place, I'm not confident it won't happen again, but I'm hoping with time, I'll get it figured out.

**Comment by martjag12** [comment]
Appreciate, workaround for now works for me.

**Comment by burkybang** [comment]
Fantastic! This morning another user reported that restarting his computer resolved the issue.
