### ISSUE TITLE
❗Vanishing fields on records 💥

### ISSUE THREAD

**Issue by HeavenlyEntity** [burkybang/SuiteAdvanced-Feedback#157]
**Describe the bug**
_A clear and concise description of what the bug is._

When loading a record with custom fields it is causing those fields to disappear when the extension is loaded.

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to sales order with custom fields under a subtab_
2. _View the fields for a split second_
3. _See the fields disappear_
4. _No more fields left_

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

The fields should not be touched and should allow for a user to have an infinite number of fields without making them disappear

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

https://github.com/burkybang/SuiteAdvanced-Feedback/assets/39228141/b1f2efdd-d9c7-4736-a839-1399782b2844

#### With Fields: Extension Disabled
![NexSnap-Jun-21-2024_12-12-44_PM](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/39228141/f59563cb-ac8c-4708-9998-a9beefff6a1d)

#### Without Fields: Extension Enabled
![NexSnap-Jun-21-2024_12-18-20_PM](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/39228141/4f1f2715-69f2-4a85-a548-f4b3b209a34f)

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
It appears that the field group is collapsed. Click on the field group heading to expand it. There will be a setting in the next version to disable collapsible field groups.

**Comment by HeavenlyEntity** [comment]
I see! Gotchya! The arrow is hard to distinguish. If you have something better for the group to indicate collapse that would be better :)

**Comment by burkybang** [comment]
Yeah, I like the animation idea. I tried that initially, but I couldn't figure out a good way to implement it due to how NetSuite's HTML is structured. I'll probably revisit that later.

I think you're right about the arrow icon. A few field groups can be collapsed natively, and I simply used the icon that NetSuite already uses in those cases. I normally try to make things look as native as possible, but NetSuite design isn't always the best, so I will consider changing the icon to something more obvious. You are not the first person who has mentioned this, so it's definitely a problem.

**Comment by HeavenlyEntity** [comment]
Yeah, Adam I would suggest using inline css to make it easier or loading in
animate.css to make it even easier.

**Comment by burkybang** [comment]
I've added a slight animation when a field group gets collapsed, and I've reduced the opacity of a collapsed field group header to make it more obvious that it's collapsed.

**Comment by HeavenlyEntity** [comment]
Sweet! Thank you sir! I look forward to trying it out! 🎉
