### ISSUE TITLE
change email address

### ISSUE THREAD

**Issue by toyloe** [burkybang/SuiteAdvanced-Feedback#166]
Hi there - was just wondering how I can change my email address?  Updating credit card information is easy, but need to update my email so I receive receipt emails.  Thank you!
-Tara

**Comment by burkybang** [comment]
If you only want to change your email address because you would like to receive receipts, I can manually change your billing email address if you send me an email: support@suiteadvanced.com

If you would like to change the email address you log in with, you'll need to cancel your subscription and purchase a new one with the new email address.

**Comment by toyloe** [comment]
Thank you for that information.  For now, I'll email [support@suiteadvanced.com] to have my billing email updated to receive emailed receipts.  Thank you!
