### ISSUE TITLE
Update Advanced HTML/PDF Template Error 

### ISSUE THREAD

**Issue by avargas94** [burkybang/SuiteAdvanced-Feedback#56]
**Describe the bug**
When you encounter an error popup message with the advanced pdf/html while in dark mode isn't readable due to the white background & white text. If you want to reproduce the issue just delete any closing html tag and attempt to save.

![image](https://user-images.githubusercontent.com/35619279/194406233-68c592ce-e72b-4da9-847b-f11d571eb1f2.png)

**Comment by burkybang** [comment]
Thanks! I will get this fixed for the next version.

**Comment by burkybang** [comment]
Here's a preview of what it will look like in the next version. I also made it so the error message is always visible instead of the user having to click the Details link to show it. One less step 😀

![image](https://user-images.githubusercontent.com/927886/194670204-c13b25b7-1885-4d65-b3b5-d605f20fcccd.png)
